config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'top#main'
  get 'top/main'
  resources :products
  resources :cart_items,only: [:create, :destroy]
  resources :carts,only: [:show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
     has_many :products
     has_many :cart_items
     has_many :cart_products, through: :cart_items, source: :product
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
    belongs_to :cart
    belongs_to :product
    
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :cart
  has_many :cart_items
  has_many :cart_products, through: :cart_items, source: :cart
    
   # def take(cart)
     #   cart_item.create(cart_id: cart.id)
   # end
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
  private
   def current_cart
       if session[:cart_id]
           cart = Cart.find(session[:cart_id])
       else
           cart = Cart.create
           session[:cart_id] = cart.id
       end
    cart
   end

helper_method :current_cart
  
end

app/controllers/cart_items_controller.rb
class CartItemsController < ApplicationController
    
    def create
     @products = Product.all
     product = Product.find(params[:product_id])
     cart = current_cart
     cart.cart_products << product
     redirect_to '/'
    end
    
    
    def destroy
     @carts = Cart.all
     cart = Cart.find(params[:product_id])
     product = Product.find_by(name: session[:cart_id])
     cart.cart_items.find_by(product_id: product.id).destroy
     redirect_to '/'
    end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
    
    def show
        @cart = Cart.all
    end
    
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
    
    def index
        @products = Product.all
    end
    
    def new
        @product = Product.new
    end
    
    def create
    name = params[:product][:name]
    price = params[:product][:price]
    
    product = Product.new(name: name,price: price)
    product.save
    redirect_to products_path
    end
    
    def destroy
    product = Product.find(params[:id])
    product.destroy
    redirect_to products_path
    end
    
    def show
        @products = Product.all
    end
    
end

app/controllers/top_controller.rb
class TopController < ApplicationController
    
    def main
        
        @products = Product.all
    
    end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/views/carts/show.html.erb
<h1>カート</h1>

<% @cartitem.each do |c| %>
<%= c.product_id %>
<p>
    <%= link_to '商品削除', "cs/#{c.id}", method: :delete %>
</p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>L7</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/products/index.html.erb
<h1>商品一覧</h1>

<% @products.each do |product| %>
<p>
    <%= link_to product.name%><%= "　　値段：#{product.price}"%>
    <%= link_to 'カートに追加', cart_items_path(product_id: product.id), method: :post %>
    <%= link_to '商品削除', "products/#{product.id}", method: :delete %>
</p>
<% end %>

app/views/products/new.html.erb
<h1>商品登録</h1>
<%= form_for @product , name: {action: :create} do |f| %>
<%= f.label :name, '商品名' %>
<%= f.text_field :name %>
<%= f.label :price, '値段' %>
<%= f.text_field :price %>

<%= f.submit '登録' %>
<% end %>

app/views/top/main.html.erb
<% @products.each do |e| %>
 <p>
     <%= form_tag cart_items_path,method: :post do %>
     <%= e.name %>
     <%= e.price %>円
     <%= hidden_field_tag :product_id, e.id %>
     数量:<%= select_tag(:qty,options_for_select((1..30)))%>
     <%= submit_tag 'カートへ追加する'%>
     <% end %>
 </p>
<% end %>

<p><%= link_to '登録', 'products/new' %></p>
<p><%= link_to '一覧', 'products#index' %></p>
<br><br>
<p><%= link_to 'カート', 'carts/show' %></p>